### ISSUE TITLE
Python 3 compatibility?

### ISSUE THREAD

**Issue by Oxylibrium** [aheadley/python-crunchyroll#14]
On running `list_anime_series(limit=5)` as shown in the example documentation on Python 3.6.4 on Windows, I get the following traceback.

Is Python 3 compatibility a goal for the project?
```
>>> api.list_anime_series(limit=5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\akash\AppData\Roaming\Python\Python36\site-packages\crunchyroll\apis\meta.py", line 41, in inner_func
    self.start_session()
  File "C:\Users\akash\AppData\Roaming\Python\Python36\site-packages\crunchyroll\apis\meta.py", line 162, in start_session
    self._android_api.start_session()
  File "C:\Users\akash\AppData\Roaming\Python\Python36\site-packages\crunchyroll\apis\android.py", line 39, in inner_func
    req_func = self._build_request(req_method, req_url, params=kwargs)
  File "C:\Users\akash\AppData\Roaming\Python\Python36\site-packages\crunchyroll\apis\android.py", line 137, in _build_request
    full_params = self._get_base_params()
  File "C:\Users\akash\AppData\Roaming\Python\Python36\site-packages\crunchyroll\apis\android.py", line 115, in _get_base_params
    for k, v in self._state_params.iteritems() \
AttributeError: 'dict' object has no attribute 'iteritems'
```
Thanks,
Oxylibrium.

**Comment by Oxylibrium** [comment]
Just noticed the python3 compat commits from a while ago and tested on master instead of the version available on PyPI. Appears to work, but can the version on PyPI be updated?
